name: Increment the version number
on:
  push:
    branches:
    - master
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Increment version
        uses: "phips28/gh-action-bump-version@v8.2.2"