name: Bump version number

on:
  push:
    branches:
    - master
  
jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: "Clean install"
        run: npm ci

      - name: "Bump app version in package.json"
        uses: "phips28/gh-action-bump-version@v8.2.2"

      - name: Exit Job
        if: ${{ failure() || cancelled() }}
        run: exit 1